return {
"                                     .oooo.                                     ",
"                                  oOOOOOOOOOOo                                  ",
"                             .oOOooOOOOOOOOOOooOOo.                             ",
"                          .oOOOOOOO oOOOOOOo OOOOOOOo.                          ",
"                         oOOoOOOOOo..OOOOOO .OOOOOOoOO.                         ",
"                        .OO OOOOOOOOOO.Oo.OOOOOOOOOO OO.                        ",
"                        .OOoOOOOOOOOOOOOOOOOOOOOOOOO.OO                         ",
"                      . oOooOOOO.oOOOOOOOOOOOOooOOOOooO. .                      ",
"                    oOOO.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOooOOO.                    ",
"                    oo.oO .ooo.oOOOOOOoOOOOOOOOOo.ooo..Oo.oo                    ",
"                    oOO.O OOoo.oo..oOooOOoooo..oo.ooOo O.OO.                    ",
"                     oO.o.OOOOOooo.ooOOOOOOoo.oooOOOOO o.O.                     ",
"                      ooO. oOOOOOOOOOOOOOOOOOOOOOOOOo oOo.                      ",
"                     .OOOOOo .OOOooOOOOOOOOOO.OOOO. oOOoOO                      ",
"                    oOooOOOo oOOOOOOOoOOOOoOOOOOOO. oOOOoOO.                    ",
"                    oOOOO.oOOOOOOOOOOOO .OOOOOOOOOOOOooOOOOo                    ",
"                 .oOoOoooOOOOOOOOOOoOO...oOOoOOOOOOOOOOoooOoOo.                 ",
"                 .oooOOOOOOOOOOOo.o..OOOOOO....oOOOOOOOOOOOooo.                 ",
"                 OO oooOOOOooo. oOoOOOoOoOOOooOo .ooOOOOOooo.OO                 ",
"               .OOooOOo  oo. O.oO OooOoOoOO OO O.oO .oo  oOOooOo.               ",
"               OooOOo..oOO.oOo.oOoO.OOoOooOo.O.Oo.OOo.OOo .OOO.oO               ",
"               O.oOO  OO.oOo.oOooOooO. Oo oO.OOooOo.oOo.OO  OO.oo               ",
"                 OOo  OooO  Oo OO. OO.oOOooOo .OO Oo  OoOO  oOo                 ",
"                 O.  OO.oOo Oo.Oo.OO. Oooo .OO.oO Oo oO..Oo  oo                 ",
"                oOO. Oo   O Oo OO.O.  oOoo  oO.OO Oo.O   Oo oOOo                ",
"                ooo. Oo   O oO..oOooo .Ooo.ooOOo oOo.O   Oo oooo                ",
"                     Oo  oO. .oO oO o..Ooooo.O..Oo  oO.  Oo                     ",
"                     OO .OoO  .O oO o..Ooooo.O..O  .OoO  Oo                     ",
"                    OOOO      .O oO Oo.Ooooo.O..O       OoOo                    ",
"                     oo      oO. oO  oO..O. .O. .Oo     .o.                     ",
"                             Oo .OOO oo  Oo.OOO. oo                             ",
"                            oOO .Ooo OO..Oo.ooO..OO.                            ",
"                                    .oo..oo                                     ",
}
